### ISSUE TITLE
Chargemol (DDEC calculator) is not a serial code

### ISSUE THREAD

**Issue by danieleongari** [lsmo-epfl/aiida-ddec#18]
Sorry that I noted just now but Chargemol can run on multiple CPUs.
In my experience going to multiple nodes make it very slow but once you run it on a single node (e.g., 28 cpus of Fidis) it uses all of them.

Therefore https://github.com/lsmo-epfl/aiida-ddec/commit/673cf221c149a0ae52cb67113be0e46d5d930e05 by @ltalirz is unjustified.

**Comment by ltalirz** [comment]
so I guess `num_machines: 1` is good, but the other two defaults can be removed (?).

It runs with MPI, correct?

**Comment by yakutovicha** [comment]
I assume it is openMP

**Comment by yakutovicha** [comment]
So one should probably set `OMP_NUM_THREADS`, as explained here: https://software.intel.com/en-us/mkl-windows-developer-guide-setting-the-number-of-threads-using-an-openmp-environment-variable

**Comment by danieleongari** [comment]
I always used the following settings and  with these it was using all the cpus of fidis (I verified 100% loading for all with `htop`):
```
ddec_options = {
    'resources': {
        'num_machines': 1
    },
    'max_wallclock_seconds': 10 * 60 * 60,
    'withmpi': False,
}
```

**Comment by danieleongari** [comment]
This means that by just running the executable it spreads the calculation on all the available nodes without using `mpirun`: this is what I'm experiencing on my localhost.
